import CommitKit
import Foundation

func printHelp() {
    let lines = [
        "Usage: commit [message]",
        "       commit --file <path>",
        "       echo <message> | commit",
        "",
        "Validates a conventional commit message against project rules.",
        "Exits 0 on success, 1 on failure.",
    ]
    print(lines.joined(separator: "\n"))
}

/// Render a CliError as `error: <message>` + bulleted suggestions, then exit 1.
/// Anything else is rethrown so genuine bugs surface a stack trace.
func fail(_ error: Error) -> Never {
    guard let cli = error as? CliError else {
        FileHandle.standardError.write(Data("error: \(error)\n".utf8))
        exit(1)
    }
    var out = "error: \(cli.message)\n"
    for suggestion in cli.suggestions {
        out += "  - \(suggestion)\n"
    }
    FileHandle.standardError.write(Data(out.utf8))
    exit(1)
}

struct Args {
    var file: String?
    var help = false
    var positional: [String] = []
}

func parseArgs(_ argv: [String]) -> Args {
    var args = Args()
    var i = 0
    while i < argv.count {
        let arg = argv[i]
        switch arg {
        case "--help", "-h":
            args.help = true
        case "--file", "-f":
            i += 1
            if i < argv.count { args.file = argv[i] }
        default:
            if arg.hasPrefix("--file=") {
                args.file = String(arg.dropFirst("--file=".count))
            } else {
                args.positional.append(arg)
            }
        }
        i += 1
    }
    return args
}

func readMessage(_ args: Args) throws -> String {
    if let file = args.file {
        return try String(contentsOfFile: file, encoding: .utf8)
    }
    if let positional = args.positional.first {
        return positional
    }
    if isatty(FileHandle.standardInput.fileDescriptor) != 0 {
        return ""
    }
    let data = FileHandle.standardInput.readDataToEndOfFile()
    return String(data: data, encoding: .utf8) ?? ""
}

/// Git auto-generates merge and revert messages; the conventional format does
/// not apply to them.
func isAutoGenerated(_ text: String) -> Bool {
    guard let subject = text.split(separator: "\n", omittingEmptySubsequences: false)
        .map({ $0.trimmingCharacters(in: .whitespaces) })
        .first(where: { !$0.isEmpty })
    else { return false }
    return subject.hasPrefix("Merge ") || subject.hasPrefix("Revert ")
}

// MARK: - Entry point

let args = parseArgs(Array(CommandLine.arguments.dropFirst()))

if args.help {
    printHelp()
    exit(0)
}

let message: String
do {
    message = try readMessage(args)
} catch {
    fail(error)
}

if message.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
    fail(CliError("no commit message provided", [
        "Pass a message as an argument, --file <path>, or via stdin",
    ]))
}

if isAutoGenerated(message) {
    exit(0)
}

// Validate only the subject line (the first non-empty, non-comment line). The
// body and footers (e.g. `BREAKING CHANGE:`) are free-form and must not be
// punctuation- or length-checked.
let subjectLine = message
    .split(separator: "\n", omittingEmptySubsequences: false)
    .map(String.init)
    .first { line in
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        return !trimmed.isEmpty && !trimmed.hasPrefix("#")
    } ?? ""

let config = CommitConfig.load()

do {
    try CommitValidator.validate(subjectLine, config: config)
} catch {
    fail(error)
}

exit(0)
