import { parseArgs } from '@std/cli/parse-args'
import { toText } from '@std/streams/to-text'
import { handleCliError, unwrap } from '../utils/cli.utils.ts'
import { CliError } from '../utils/error.utils.ts'
import { safe, safeAsync } from '../utils/safe.utils.ts'
import { loadConfig } from './commit.config.ts'
import { validateCommitMessage } from './commit.validator.ts'

const args = parseArgs(Deno.args, {
  string: ['file'],
  alias: { f: 'file', h: 'help' },
  boolean: ['help'],
})

const printHelp = (): void => {
  const lines = [
    'Usage: commit [message]',
    '       commit --file <path>',
    '       echo <message> | commit',
    '',
    'Validates a conventional commit message against project rules.',
    'Exits 0 on success, 1 on failure.',
  ]

  console.log(lines.join('\n'))
}

const readMessage = async (): Promise<string> => {
  if (args.file) {
    return await Deno.readTextFile(args.file)
  }

  const positional = args._[0]
  if (positional !== undefined) {
    return String(positional)
  }

  if (Deno.stdin.isTerminal()) {
    return ''
  }

  return await toText(Deno.stdin.readable)
}

if (args.help) {
  printHelp()
  Deno.exit(0)
}

const message = unwrap(await safeAsync(() => readMessage()))
if (!message.trim()) {
  handleCliError(new CliError('no commit message provided', ['Pass a message as an argument, --file <path>, or via stdin']))
}

// Git auto-generates merge and revert messages; the conventional format does not apply to them.
const isAutoGenerated = (text: string): boolean => {
  const subject = text.split('\n').find((line) => line.trim() !== '')
  if (!subject) return false

  const trimmed = subject.trim()
  return trimmed.startsWith('Merge ') || trimmed.startsWith('Revert ')
}

if (isAutoGenerated(message)) {
  Deno.exit(0)
}

// Validate only the subject line (the first non-empty line). The body and
// footers (e.g. `BREAKING CHANGE:`) are free-form and must not be punctuation-
// or length-checked. Git comment lines (`#`) are stripped by git before the
// hook sees them, but guard anyway.
const subjectLine = message
  .split('\n')
  .find((line) => line.trim() !== '' && !line.trimStart().startsWith('#')) ?? ''

const config = unwrap(safe(() => loadConfig()))

unwrap(safe(() => validateCommitMessage(subjectLine, config)))

Deno.exit(0)
